# Generated by Django 4.1 on 2022-08-17 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_twitterauthflowstate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="twitterauthtoken",
            name="oauth_token_secret",
        ),
    ]
