# Generated by Django 4.1 on 2022-08-16 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('humanspace_app', '0004_topic_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitteruser',
            name='id',
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
