# Generated by Django 4.1 on 2022-08-16 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humanspace_app', '0005_remove_twitteruser_id_alter_twitteruser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitteruser',
            name='twitter_oauth_token',
        ),
        migrations.RemoveField(
            model_name='twitteruser',
            name='user',
        ),
        migrations.DeleteModel(
            name='TwitterAuthToken',
        ),
        migrations.DeleteModel(
            name='TwitterUser',
        ),
    ]
